### ISSUE TITLE
CFBundleIdentifier 'org.cocos2dx.Chapter 2' contains illegal character ' '

### ISSUE THREAD

**Issue by lvyile** [chukong/programmers-guide-samples#13]
(null): error: CFBundleIdentifier 'org.cocos2dx.Chapter 2' contains illegal character ' ' invalid bundle identifier 'org.cocos2dx.Chapter 2'

The better one is "org.cocos2dx.guide.c2"

**Comment by slackmoehrle** [comment]
I fixed the info.plist file. I'm not sure why I don't see this same error. I run this code all the time. It will be part of my next push.
