### ISSUE TITLE
No Android Project

### ISSUE THREAD

**Issue by darkdukey** [chukong/programmers-guide-samples#14]
I think we should provide android project as well, so people using windows/linux can also try it out.

**Comment by slackmoehrle** [comment]
ok, I will ask Minggo to see if he can have someone from his team do this quicker than I can.

**Comment by Michael-Hamburger** [comment]
you should add win32 project also ...

**Comment by slackmoehrle** [comment]
Thanks Michael
On the list :-)

* Sent using 100% recycled packets *




On Sat, Feb 21, 2015 at 5:33 AM -0800, "Michael" <notifications@github.com> wrote:












you should add win32 project also ...

**Comment by andyque** [comment]
@slackmoehrle  @darkdukey 
I think programmers-guide-samples repository should port to all the supported platforms.

**Comment by gordeyg** [comment]
Sad it is not ported yet.

**Comment by slackmoehrle** [comment]
We now have an android version in the v3.8 branch.
