### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by rafaelsaqueli** [chukong/programmers-guide-samples#20]
Everything was fine, but when I ran "cd libs / cocos2d-x" as it is in the instructions, an error occurred: "No such file or directory" and can't run the examples. Can anyone help me?

**Comment by slackmoehrle** [comment]
The programmers guide samples does NOT include cocos2d-x. You need to add that yourself or use the prebuilt libraries. We had talked about making this easier, just have not gotten to it yet.

**Comment by rafaelsaqueli** [comment]
Ok, I did it and follow the other steps, but when I run the examples on Xcode, occur another error (image). 

** I'm using Xcode 6.3.1

![screen shot 2015-08-25 at 6 34 38 pm](https://cloud.githubusercontent.com/assets/3995179/9480223/4ea6d8f2-4b58-11e5-9768-2a25fcf91e85.png)

![screen shot 2015-08-25 at 6 39 38 pm](https://cloud.githubusercontent.com/assets/3995179/9480286/b81c227e-4b58-11e5-8bab-ed73ad20c8aa.png)

**Comment by slackmoehrle** [comment]
have you done a `Clean` and `Build`?

**Comment by slackmoehrle** [comment]
I can reproduce this, so I am going to file a bug for this.

**Comment by rafaelsaqueli** [comment]
OK, Thank you so much!

**Comment by slackmoehrle** [comment]
I have now fixed this and changed these samples to use the pre-built libraries in the v3.8 branch.
