### ISSUE TITLE
Chapter 9 - axe.c3b will not render as Sprite3d nor AttachNode. (android vm)

### ISSUE THREAD

**Issue by sql4088** [chukong/programmers-guide-samples#21]
Just wanted to tell you that I love this game engine, thank you very much.

In Chapter 9, Axe.c3b will not render on screen. (Android VM), I believe it's a problem with the Model file.

I tested a render with the orc.c3b model (successfully rendered on the screen).
  This code renders the Orc:
	auto sprite = Sprite3D::create("orc.c3b"); //C3B file, created with the FBX-converter
	sprite->setPosition(Vec2(origin.x + _visibleSize.width / 2, origin.y + _visibleSize.height / 2).x,
		Vec2(origin.x + _visibleSize.width / 2, origin.y + _visibleSize.height / 2).y);
	this->addChild(sprite, 1); //adds sprite to scene, z-index: 1

I unsuccessfully tried to attach the axe to the orc using the getAttachNode method (it did not render an attachment on the Orc,) 
  This code does not render the axe:
auto sp = Sprite3D::create("axe.c3b");
sprite->getAttachNode("Bip001 R Hand")->addChild(sp);

I unsuccessfully tried to render ONLY the axe.c3b as a Sprite3D model (not as an attachment).
  This code does not render the axe:
	auto sprite = Sprite3D::create("axe.c3b");
	sprite->setPosition(Vec2(origin.x + _visibleSize.width / 2, origin.y + _visibleSize.height / 2).x,
		Vec2(origin.x + _visibleSize.width / 2, origin.y + _visibleSize.height / 2).y);
	this->addChild(sprite, 1); //adds sprite to scene, z-index: 1

**Comment by slackmoehrle** [comment]
I am not sure about this, but let me ask @super626 to help.

**Comment by slackmoehrle** [comment]
This has now been fixed in the v3.8 branch.
