### ISSUE TITLE
The file “Chapter 7 Mac-Info.plist” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by solodon4** [chukong/programmers-guide-samples#25]
ProcessInfoPlistFile Library/Developer/Xcode/DerivedData/Programmers_Guide-acdskudnvyrpfjcxnzscpboztgnx/Build/Products/Debug/Chapter\ 7\ Mac.app/Contents/Info.plist Chapter\ 7\ Mac-Info.plist
    cd Projects/Examples/cocos2d/programmers-guide-samples/proj.ios_mac
    builtin-infoPlistUtility Projects/Examples/cocos2d/programmers-guide-samples/proj.ios_mac/Chapter\ 7\ Mac-Info.plist -genpkginfo Library/Developer/Xcode/DerivedData/Programmers_Guide-acdskudnvyrpfjcxnzscpboztgnx/Build/Products/Debug/Chapter\ 7\ Mac.app/Contents/PkgInfo -expandbuildsettings -platform macosx -o Library/Developer/Xcode/DerivedData/Programmers_Guide-acdskudnvyrpfjcxnzscpboztgnx/Build/Products/Debug/Chapter\ 7\ Mac.app/Contents/Info.plist

error: could not read data from 'Projects/Examples/cocos2d/programmers-guide-samples/proj.ios_mac/Chapter 7 Mac-Info.plist': The file “Chapter 7 Mac-Info.plist” couldn’t be opened because there is no such file.

**Comment by slackmoehrle** [comment]
Let me look into this.

**Comment by slackmoehrle** [comment]
The chapters are not unified into one executable. This is no longer an issue.
