### ISSUE TITLE
Some chapters fail to load resources

### ISSUE THREAD

**Issue by solodon4** [chukong/programmers-guide-samples#26]
in Chapter 6: clicking on "Label" has auto myLabel2 = Label::createWithTTF("LabelTTF", "Marker Felt.ttf", 32); return nullptr probably due to inability to locate the font.

in Chapter 9: auto sprite = Sprite3D::create("boss.c3b"); fails - I can see such file in one of the subfolders, but they are not looked into at run-time

**Comment by slackmoehrle** [comment]
This is now fixed in the v3.8 branch.
